id: asdf://asdf-format.org/wcs/manifests/wcs-1.0.0
extension_uri: asdf://asdf-format.org/wcs/extensions/wcs-1.0.0
title: WCS extension 1.0.0
description: |-
  A set of tags for serializing wcs.
tags:
- tag_uri: tag:stsci.edu:asdf/wcs/celestial_frame-1.0.0
  schema_uri: http://stsci.edu/schemas/asdf/wcs/celestial_frame-1.0.0
  title: Represents a celestial frame.
  description: Represents a celestial frame.
- tag_uri: tag:stsci.edu:asdf/wcs/composite_frame-1.0.0
  schema_uri: http://stsci.edu/schemas/asdf/wcs/composite_frame-1.0.0
  title: Represents a set of frames.
  description: Represents a set of frames.
- tag_uri: tag:stsci.edu:asdf/wcs/spectral_frame-1.0.0
  schema_uri: http://stsci.edu/schemas/asdf/wcs/spectral_frame-1.0.0
  title: Represents a spectral frame.
  description: Represents a spectral frame.
- tag_uri: tag:stsci.edu:asdf/wcs/step-1.0.0
  schema_uri: http://stsci.edu/schemas/asdf/wcs/step-1.0.0
  title: Describes a single step of a WCS transform pipeline.
  description: Describes a single step of a WCS transform pipeline.
- tag_uri: tag:stsci.edu:asdf/wcs/wcs-1.0.0
  schema_uri: http://stsci.edu/schemas/asdf/wcs/wcs-1.0.0
  title: A system for describing generalized world coordinate transformations.
  description: ASDF WCS is a way of specifying transformations (usually from detector
    space to world coordinate space and back) by using the transformations in the
    `transform-schema` module.
